name: Update Proxies

on:
  schedule:
    - cron: '0 0 * * *'   # ежедневно в 00:00 UTC
  workflow_dispatch:     # ручной запуск

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false   # обязательно, чтобы использовать PAT для push

      - name: Fetch original YAML
        run: |
          curl -fsSL https://raw.githubusercontent.com/xyfqzy/free-nodes/refs/heads/main/nodes/clash.yaml -o full.yaml

      - name: Extract proxies block
        run: |
          python3 - <<'PY'
          import re, sys
          # читаем полный YAML
          txt = open('full.yaml', 'rb').read().decode('utf-8', errors='replace').splitlines(keepends=True)
          start = -1
          for i, line in enumerate(txt):
              if re.match(r'^[ \t]*proxies\s*:', line):
                  start = i
                  break
          if start == -1:
              open('proxies.yaml', 'w', encoding='utf-8').write('proxies: []\n')
              print('No proxies block found, wrote empty proxies: []')
              sys.exit(0)
          # находим конец блока
          end = len(txt)
          for j in range(start+1, len(txt)):
              if re.match(r'^[^\s].*:', txt[j]):
                  end = j
                  break
          open('proxies.yaml', 'w', encoding='utf-8').write(''.join(txt[start:end]))
          print(f'Extracted proxies block lines {start+1}-{end}')
          PY

      - name: Preview extracted block
        run: sed -n '1,200p' proxies.yaml || true

      - name: Commit and push changes
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add proxies.yaml
          git diff --cached --quiet || git commit -m "Update proxies"
          git push https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}.git HEAD:main
